#YamlMime:PythonReference
api_name: []
items:
- _type: class
  children: []
  class: cntk.train.training_session.TestConfig
  fullName: cntk.train.training_session.TestConfig
  inheritance:
  - inheritance:
    - type: builtins.object
    type: cntk.cntk_py.TestConfig
  langs:
  - python
  module: cntk.train.training_session
  name: TestConfig
  source:
    id: TestConfig
    path: \cntk\train\training_session.py
    remote:
      branch: master
      path: \cntk\train\training_session.py
      repo: https://github.com/Microsoft/CNTK.git
    startLine: 93
  summary: 'Bases: `cntk.cntk_py.TestConfig`

    A test configuration for the training session.'
  syntax:
    content: TestConfig(self, source, mb_size=None)
    parameters:
    - description: minibatch source used for testing
      id: source
      type:
      - MinibatchSource
    - description: minibatch schedule for testing
      id: schedule
      type:
      - minibatch_size_schedule
  type: Class
  uid: cntk.train.training_session.TestConfig
references: []
